# Generated by Django 4.1.1 on 2022-11-27 20:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "ingredient_id",
                    models.UUIDField(
                        default=uuid.UUID("10c34cb2-0099-450c-aaa9-af62e79a915f"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("vegetarian", models.BooleanField(default=False)),
                ("calories", models.PositiveSmallIntegerField(default=0)),
                ("fat", models.PositiveSmallIntegerField(default=0)),
                ("protein", models.PositiveSmallIntegerField(default=0)),
                (
                    "units",
                    models.CharField(
                        choices=[
                            ("CUP", "cups"),
                            ("TBP", "table spoon"),
                            ("TSP", "tea spoon"),
                            ("DSH", "dash"),
                            ("PCH", "pinch"),
                            ("LBS", "pound"),
                            ("OZS", "ounce"),
                            ("GRM", "gram"),
                            ("SLC", "slice"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
