# Generated by Django 4.1.1 on 2022-10-06 03:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "ingredient_id",
                    models.UUIDField(
                        default=uuid.UUID("db68f6b2-7697-4315-9d62-599076dc54f9"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("vegetarian", models.BinaryField(default=False)),
                ("calories", models.SmallIntegerField()),
                ("fat", models.SmallIntegerField()),
                ("protein", models.SmallIntegerField()),
                (
                    "units",
                    models.CharField(
                        choices=[
                            ("CUP", "cups"),
                            ("TBP", "table spoon"),
                            ("TSP", "tea spoon"),
                            ("DSH", "dash"),
                            ("PCH", "pinch"),
                            ("LBS", "pound"),
                            ("OZS", "ounce"),
                            ("GRM", "gram"),
                            ("SLC", "slice"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "create_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modify_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
