# Generated by Django 4.1.1 on 2022-10-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="amount",
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
