# Generated by Django 4.1.1 on 2022-12-22 02:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.UUIDField(
                default=uuid.UUID("a0d6bbe8-6267-43c7-aa4e-0c3b40c917df"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
