version: '3.8'

services:

  db:
    image: postgres:15-alpine
    env_file:
      - ./macros_backend/.env
    ports:
      - "5432:5432"
  
  backend:
    image: macros-backend
    env_file:
      - ./macros_backend/.env
    environment:
      - DEBUG_MODE=0
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    build: ./macros_backend/Dockerfile
    ports:
      - "8000:8000"
    command: > 
      sh -c "python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  
  frontend:
    image: macros-frontend
    env_file: 
      - ./frontend/.env
    build: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    command: npm run start
    depends_on: 
      - backend