# Generated by Django 4.1.1 on 2022-10-28 01:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "recipe_id",
                    models.UUIDField(
                        default=uuid.UUID("9e3c144c-54fb-4e88-b0bf-86c6251fb283"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "recipe_name",
                    models.CharField(default="Recipe", max_length=80, unique=True),
                ),
                ("creator", models.CharField(max_length=80, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BF", "Breakfast"),
                            ("LC", "Lunch"),
                            ("DN", "Dinner"),
                            ("SK", "Snack"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=500, null=True)),
                (
                    "create_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
