# Generated by Django 4.1.1 on 2022-11-12 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("95c54412-a1a7-476a-a43f-a09a3590fe0e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
