# Generated by Django 4.1.1 on 2022-09-23 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "ingredient_id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("vegetarian", models.BinaryField(default=False)),
                ("calories", models.SmallIntegerField()),
                ("fat", models.SmallIntegerField()),
                ("protein", models.SmallIntegerField()),
                (
                    "units",
                    models.CharField(
                        choices=[
                            ("CUP", "cups"),
                            ("TBP", "table spoon"),
                            ("TSP", "tea spoon"),
                            ("DSH", "dash"),
                            ("PCH", "pinch"),
                            ("LBS", "pound"),
                            ("OZS", "ounce"),
                            ("GRM", "gram"),
                            ("SLC", "slice"),
                        ],
                        max_length=3,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "Creation date & time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "Last modified date & time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_name", models.CharField(max_length=25, unique=True)),
                (
                    "height",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "body_fat",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("LGN", "low gain"),
                            ("MGN", "meduim gain"),
                            ("HGN", "high gain"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "Creation date & time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "Last modified date & time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="id",
        ),
        migrations.AddField(
            model_name="recipe",
            name="Creation date & time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="recipe",
            name="Last modified date & time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="recipe",
            name="creator",
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default="10000000-0000-0000-0000-000000000000",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
