# Generated by Django 4.1.1 on 2022-09-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_ingredient_user_remove_recipe_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="Creation date & time",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="Last modified date & time",
            new_name="modify_date",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="Creation date & time",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="Last modified date & time",
            new_name="modify_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Last modified date & time",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Creation date & time",
            new_name="modify_date",
        ),
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_type",
            field=models.CharField(
                choices=[("BF", "Breakfast"), ("SK", "Snack"), ("SM", "Standard Meal")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="user",
            name="goal",
            field=models.CharField(
                choices=[
                    ("-3", "Very rapid loss"),
                    ("-2", "Rapid loss"),
                    ("-1", "Moderate loss"),
                    ("0", "Maintain"),
                    ("1", "Moderate gain"),
                    ("2", "Rapid gain"),
                    ("3", "Very rapid gain"),
                ],
                default="0",
                max_length=2,
            ),
        ),
    ]
