# Generated by Django 4.1.1 on 2022-10-05 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_ingredient_ingredient_id_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.UUIDField(
                default=uuid.UUID("552115d3-31fa-463d-94f1-c304eec32158"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("1a03c13e-d4ff-4ec8-8b22-cbe5729dc7ed"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("faeb9a24-a9d8-488d-90b8-a67a3cecc63c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
