# Generated by Django 4.1.1 on 2022-11-12 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipe_recipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("5ba9809a-1dab-4723-87e1-475aedaf981f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
