# Generated by Django 4.1.1 on 2022-10-05 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_ingredient_ingredient_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.UUIDField(
                default=uuid.UUID("c5ec6e5d-0ca4-4d55-b210-1462a4be4a5e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("a3348001-ecd1-4bdf-a530-5ea1b40cb7f6"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("ea57ec8e-8b9f-412f-9024-ced162d72245"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
