# Generated by Django 4.1.1 on 2022-10-06 02:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_ingredient_ingredient_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="ingredient_id",
            field=models.UUIDField(
                default=uuid.UUID("0b741e51-3ca9-4ff0-a77b-ed9914e33c45"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("d9b51dfb-34c4-4af0-bacb-1ce60edfba65"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("437b469e-71df-4664-ab34-8d3603dc5e44"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
