# Generated by Django 4.1.1 on 2022-10-06 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_ingredient_ingredient_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("8f02a89d-cd56-494f-a67e-12c5ca76914c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
