# Generated by Django 4.1.1 on 2022-10-26 03:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_delete_ingredient_delete_user_alter_recipe_recipe_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="name",
            new_name="recipe_name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="recipe_type",
        ),
        migrations.AddField(
            model_name="recipe",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("BF", "Breakfast"),
                    ("LC", "Lunch"),
                    ("DN", "Dinner"),
                    ("SK", "Snack"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="create_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="recipe_id",
            field=models.UUIDField(
                default=uuid.UUID("444361ae-899e-4d81-b1dd-8d55db19f925"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
